## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/api/*"
  to = "http://183.131.108.116:3000/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}

# Rewrite a path
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
